# fly.toml app configuration file generated for cl4p-tp on 2024-01-17T15:19:59Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "cl4p-tp"
primary_region = "lax"

[build]

[http_service]
  internal_port = 7860
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024

[env]
  API_ENDPOINT         = "https://api.j3nkn5.cc/"
  LLM_SERVICE          = "j3nkn5"
  BOT_SHUTUP_PREFIX    = "@"
  ADMIN_ROLE_NAME      = "Admin"
  MODEL_NAME           = "mistralai/Mixtral-8x7B-Instruct-v0.1"
  DEBUG                = "true"
  MODEL_CONTEXT_LENGTH = "30000"
  SYSTEM_MESSAGE       = "You are a scholar. You respond with reference to the given context. Do not mention the context."

[checks]
  [checks.are_you_there]
    grace_period = "30s"
    interval = "15s"
    method = "get"
    path = "/status"
    port = 7860
    timeout = "10s"
    type = "http"